# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: helloworld.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x10helloworld.proto\x12\nhelloworld"]\n\rResizeRequest\x12\x0e\n\x06\x62ucket\x18\x01 \x01(\t\x12\r\n\x05input\x18\x02 \x01(\t\x12\x0e\n\x06output\x18\x03 \x01(\t\x12\r\n\x05width\x18\x04 \x01(\r\x12\x0e\n\x06height\x18\x05 \x01(\r"k\n\x0bResizeReply\x12\x0f\n\x07message\x18\x01 \x01(\t\x12.\n\x06status\x18\x02 \x01(\x0e\x32\x1e.helloworld.ResizeReply.Status"\x1b\n\x06Status\x12\x06\n\x02OK\x10\x00\x12\t\n\x05\x45RROR\x10\x01\x32I\n\x07Resizer\x12>\n\x06Resize\x12\x19.helloworld.ResizeRequest\x1a\x17.helloworld.ResizeReply"\x00\x42\x30\n\x1bio.grpc.examples.helloworldB\x0fHelloWorldProtoP\x01\x62\x06proto3'
)


_RESIZEREQUEST = DESCRIPTOR.message_types_by_name["ResizeRequest"]
_RESIZEREPLY = DESCRIPTOR.message_types_by_name["ResizeReply"]
_RESIZEREPLY_STATUS = _RESIZEREPLY.enum_types_by_name["Status"]
ResizeRequest = _reflection.GeneratedProtocolMessageType(
    "ResizeRequest",
    (_message.Message,),
    {
        "DESCRIPTOR": _RESIZEREQUEST,
        "__module__": "helloworld_pb2"
        # @@protoc_insertion_point(class_scope:helloworld.ResizeRequest)
    },
)
_sym_db.RegisterMessage(ResizeRequest)

ResizeReply = _reflection.GeneratedProtocolMessageType(
    "ResizeReply",
    (_message.Message,),
    {
        "DESCRIPTOR": _RESIZEREPLY,
        "__module__": "helloworld_pb2"
        # @@protoc_insertion_point(class_scope:helloworld.ResizeReply)
    },
)
_sym_db.RegisterMessage(ResizeReply)

_RESIZER = DESCRIPTOR.services_by_name["Resizer"]
if _descriptor._USE_C_DESCRIPTORS == False:

    DESCRIPTOR._options = None
    DESCRIPTOR._serialized_options = (
        b"\n\033io.grpc.examples.helloworldB\017HelloWorldProtoP\001"
    )
    _RESIZEREQUEST._serialized_start = 32
    _RESIZEREQUEST._serialized_end = 125
    _RESIZEREPLY._serialized_start = 127
    _RESIZEREPLY._serialized_end = 234
    _RESIZEREPLY_STATUS._serialized_start = 207
    _RESIZEREPLY_STATUS._serialized_end = 234
    _RESIZER._serialized_start = 236
    _RESIZER._serialized_end = 309
# @@protoc_insertion_point(module_scope)
